development:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: phillipjones
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: phillipjones
  password:

production:
    adapter: postgresql
    encoding: unicode
    database: sample_app
    pool: 5
    username: phillipjones
    password:
