# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa9281d294349b179d369884ef98538e86f35960273ec59e6415b0cb3fcea3c4d5cb3c2a2a9738ce895de91a6c0c8c41b1a2553c435dec60066d6583183d5c7d

test:
  secret_key_base: 6c842f3ddc666ef4fa5c01333c70030470cb8c171f9bea0895fa10dfee5d7cfad93e62db0fdfd326cf49f19d2983d8f0e704a90d760b3de44f2bb92fc59d87ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
